// Package uploader — tests for remote CAR verification.
package uploader

import (
	"context"
	"bytes"
	"encoding/binary"
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/LWDJD/ipfar-uploader/arweave"
	"github.com/LWDJD/ipfar-uploader/car"
	"github.com/ipfs/go-cid"
)

// newMockGateway starts an HTTP test server that serves the given CAR bytes
// (with proper Range support) and returns a GatewayClient pointed at it.
func newMockGateway(t *testing.T, carBytes []byte) (*arweave.GatewayClient, string, func()) {
	t.Helper()

	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		// Support HEAD for file size
		if r.Method == http.MethodHead {
			w.Header().Set("Content-Length", fmt.Sprintf("%d", len(carBytes)))
			w.WriteHeader(http.StatusOK)
			return
		}

		// Support Range requests
		rangeHeader := r.Header.Get("Range")
		if rangeHeader != "" {
			var start, end int64
			_, err := fmt.Sscanf(rangeHeader, "bytes=%d-%d", &start, &end)
			if err != nil {
				// Try "bytes=%d-" format
				_, err = fmt.Sscanf(rangeHeader, "bytes=%d-", &start)
				if err != nil {
					w.WriteHeader(http.StatusBadRequest)
					return
				}
				end = int64(len(carBytes)) - 1
			}

			if start >= int64(len(carBytes)) {
				w.WriteHeader(http.StatusRequestedRangeNotSatisfiable)
				return
			}
			if end >= int64(len(carBytes)) {
				end = int64(len(carBytes)) - 1
			}

			w.Header().Set("Content-Range",
				fmt.Sprintf("bytes %d-%d/%d", start, end, len(carBytes)))
			w.Header().Set("Content-Length", fmt.Sprintf("%d", end-start+1))
			w.WriteHeader(http.StatusPartialContent)
			w.Write(carBytes[start : end+1])
			return
		}

		// Full response
		w.Header().Set("Content-Length", fmt.Sprintf("%d", len(carBytes)))
		w.WriteHeader(http.StatusOK)
		w.Write(carBytes)
	})

	server := httptest.NewServer(mux)
	client := arweave.NewGatewayClient(server.URL)

	// The gateway client expects the URL to not have a trailing slash,
	// and DownloadTransactionDataRange appends "/{txID}".
	// Our mock uses "/" as catch-all, so any txID works.
	txID := "mock-tx-id"

	cleanup := func() {
		server.Close()
	}

	return client, txID, cleanup
}

// TestVerifyRemoteCAR_LegacyFormat tests that VerifyRemoteCAR correctly
// validates a CAR v2 file generated by the uploader's own builder (which
// uses the legacy "car\x02" pragma and varint-format v1 header).
func TestVerifyRemoteCAR_LegacyFormat(t *testing.T) {
	// Build a CAR v2 file locally
	carBytes, rootCID, err := car.CreateCarV2FromBytes([]byte("hello world test data"))
	if err != nil {
		t.Fatalf("failed to create CAR v2: %v", err)
	}
	_ = carBytes

	gateway, txID, cleanup := newMockGateway(t, carBytes)
	defer cleanup()

	verified, err := VerifyRemoteCAR(context.Background(), gateway, txID, rootCID.String())
	if err != nil {
		t.Fatalf("VerifyRemoteCAR failed: %v", err)
	}
	if !verified {
		t.Fatal("expected verified=true, got false")
	}
}

// TestVerifyRemoteCAR_WrongRootCID tests that a wrong root CID triggers an error.
func TestVerifyRemoteCAR_WrongRootCID(t *testing.T) {
	carBytes, _, err := car.CreateCarV2FromBytes([]byte("some data"))
	if err != nil {
		t.Fatalf("failed to create CAR v2: %v", err)
	}

	gateway, txID, cleanup := newMockGateway(t, carBytes)
	defer cleanup()

	// Use a completely unrelated CID
	wrongCID := "bafkreihdwdcefgh4dykjdu2qoz3zhvxhi6h33jqujfqmywf5teehzzzzzz"
	verified, err := VerifyRemoteCAR(context.Background(), gateway, txID, wrongCID)
	if err == nil {
		t.Fatal("expected error for wrong root CID, got nil")
	}
	if verified {
		t.Fatal("expected verified=false for wrong root CID")
	}
	t.Logf("correctly rejected wrong CID: %v", err)
}

// TestVerifyRemoteCAR_InvalidCID tests that an invalid CID string is caught.
func TestVerifyRemoteCAR_InvalidCID(t *testing.T) {
	carBytes, _, err := car.CreateCarV2FromBytes([]byte("data"))
	if err != nil {
		t.Fatalf("failed to create CAR v2: %v", err)
	}

	gateway, txID, cleanup := newMockGateway(t, carBytes)
	defer cleanup()

	verified, err := VerifyRemoteCAR(context.Background(), gateway, txID, "not-a-valid-cid!!!")
	if err == nil {
		t.Fatal("expected error for invalid CID")
	}
	if verified {
		t.Fatal("expected verified=false")
	}
	t.Logf("correctly rejected invalid CID: %v", err)
}

// TestVerifyRemoteCAR_EmptyFile tests error handling when the remote file is
// too small to be a valid CAR.
func TestVerifyRemoteCAR_EmptyFile(t *testing.T) {
	carBytes := make([]byte, 10) // too small
	gateway, txID, cleanup := newMockGateway(t, carBytes)
	defer cleanup()

	verified, err := VerifyRemoteCAR(context.Background(), gateway, txID, "bafkreihdwdcefgh4dykjdu2qoz3zhvxhi6h33jqujfqmywf5teehzzzzzz")
	if err == nil {
		t.Fatal("expected error for empty/small file")
	}
	if verified {
		t.Fatal("expected verified=false")
	}
	t.Logf("correctly rejected small file: %v", err)
}

// TestVerifyRemoteCAR_CBORFormat tests verification of a CAR v2 file that uses
// the standard CBOR pragma and CBOR-format v1 header (as generated by go-car/v2).
// This is the case that was previously failing with "unsupported CAR v1 version: 99".
func TestVerifyRemoteCAR_CBORFormat(t *testing.T) {
	carBytes, rootCID := buildCBORFormatCAR(t)

	gateway, txID, cleanup := newMockGateway(t, carBytes)
	defer cleanup()

	verified, err := VerifyRemoteCAR(context.Background(), gateway, txID, rootCID.String())
	if err != nil {
		t.Fatalf("VerifyRemoteCAR failed for CBOR-format CAR: %v", err)
	}
	if !verified {
		t.Fatal("expected verified=true for CBOR-format CAR")
	}
	t.Log("CBOR-format CAR v2 verified successfully")
}

// TestVerifyRemoteCAR_MultipleRequests tests that the remote reader handles
// multiple sequential small ReadAt calls correctly (byte-by-byte varint reads).
func TestVerifyRemoteCAR_MultipleRequests(t *testing.T) {
	carBytes, rootCID, err := car.CreateCarV2FromBytes([]byte("multi-request test payload"))
	if err != nil {
		t.Fatalf("failed to create CAR v2: %v", err)
	}

	// Use a counting wrapper to verify multiple HTTP requests are made
	gateway, txID, cleanup := newMockGateway(t, carBytes)
	defer cleanup()

	verified, err := VerifyRemoteCAR(context.Background(), gateway, txID, rootCID.String())
	if err != nil {
		t.Fatalf("VerifyRemoteCAR failed: %v", err)
	}
	if !verified {
		t.Fatal("expected verified=true")
	}
}

// =============================================================================
// Helpers for building CBOR-format CAR v2 files
// =============================================================================

// buildCBORFormatCAR builds a minimal CAR v2 file using the standard CBOR pragma
// and CBOR-format v1 header (as go-car/v2 would generate). Returns the CAR bytes
// and the root CID.
func buildCBORFormatCAR(t *testing.T) ([]byte, cid.Cid) {
	t.Helper()

	// We build a valid CAR v1 block then wrap it in CBOR-format v2.
	// Use the uploader's builder to get a valid root CID and data block,
	// then re-encode using CBOR format.

	builder := car.NewCarV2Builder()
	rootCID, err := builder.AddRawBlock([]byte("hello cbor car v2"))
	if err != nil {
		t.Fatalf("AddRawBlock failed: %v", err)
	}

	// Manually encode the data block
	rootCIDBytes := rootCID.Bytes()
	blockData := []byte("hello cbor car v2")
	sectionLen := uint64(len(rootCIDBytes) + len(blockData))

	var dataBuf bytes.Buffer
	// varint(sectionLen)
	dataBuf.Write(encodeVarint(sectionLen))
	// CID bytes
	dataBuf.Write(rootCIDBytes)
	// block data
	dataBuf.Write(blockData)

	// Build CBOR v1 header:
	// {"roots": [<CID>], "version": 1}
	// CBOR layout:
	//   0xa2 = map(2)
	//     0x65 72 6f 6f 74 73 = "roots" (string of length 5)
	//     0x81 = array(1)
	//       0xd8 0x2a = tag(42)
	//       0x58 0x22 = bytes(34) — CID bytes with multibase prefix
	//       0x00 <34 bytes of CID>  — multibase identity prefix + raw CID
	//     0x67 76 65 72 73 69 6f 6e = "version" (string of length 7)
	//     0x01 = uint(1)

	// Build CBOR v1 header content
	cborContent := buildCBORV1Header(rootCIDBytes)

	// CBOR v1 header: varint(CBOR length) + CBOR data
	v1HeaderBytes := append(encodeVarint(uint64(len(cborContent))), cborContent...)

	// Build CBOR v2 pragma + header
	// Standard pragma: 0x0a (uint(10) — outer CBOR length), then CBOR: {"version": 2}
	// This is 11 bytes: 0a a1 67 76 65 72 73 69 6f 6e 02
	cborPragma := []byte{
		0x0a,                                           // uint(10) — outer CBOR map length
		0xa1,                                           // map(1)
		0x67,                                           // string(7)
		0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, // "version"
		0x02,                                           // uint(2)
	}

	// Standard v2 header (40 bytes): Characteristics[16] + DataOffset[8] + DataSize[8] + IndexOffset[8]
	pragmaLen := uint64(len(cborPragma))
	v2HeaderLen := uint64(40)
	v1HeaderLen := uint64(len(v1HeaderBytes))
	dataOffset := pragmaLen + v2HeaderLen
	dataSize := v1HeaderLen + uint64(dataBuf.Len())
	indexOffset := dataOffset + dataSize

	// Build a minimal valid index
	// Index entries: varint(entryLen) + varint(cidLen) + CID + varint(offset)
	// offset is relative to data section start, and in our case the v1 header is part of data section
	// so the block offset = v1HeaderLen
	indexEntryContent := append(encodeVarint(uint64(len(rootCIDBytes))), rootCIDBytes...)
	indexEntryContent = append(indexEntryContent, encodeVarint(v1HeaderLen)...)
	indexBuf := append(encodeVarint(uint64(len(indexEntryContent))), indexEntryContent...)
	// Pad to 8 bytes
	padLen := (8 - (len(indexBuf) % 8)) % 8
	for i := 0; i < padLen; i++ {
		indexBuf = append(indexBuf, 0)
	}
	indexSize := uint64(len(indexBuf))

	v2Header := make([]byte, 40)
	// Characteristics [0:16] — all zeros
	binary.LittleEndian.PutUint64(v2Header[16:24], dataOffset)
	binary.LittleEndian.PutUint64(v2Header[24:32], dataSize)
	binary.LittleEndian.PutUint64(v2Header[32:40], indexOffset)
	// Note: IndexSize is NOT in standard header — it's computed as fileSize - indexOffset

	var carBuf bytes.Buffer
	carBuf.Write(cborPragma)
	carBuf.Write(v2Header)
	carBuf.Write(v1HeaderBytes)
	carBuf.Write(dataBuf.Bytes())
	carBuf.Write(indexBuf)

	result := carBuf.Bytes()

	// Verify the fileSize matches
	_ = indexSize
	_ = result

	return result, rootCID
}

// buildCBORV1Header builds the CBOR content for a CAR v1 header.
// Format: {"roots": [<CID>], "version": 1}
func buildCBORV1Header(cidBytes []byte) []byte {
	// CID bytes with multibase identity prefix (0x00)
	cidWithPrefix := append([]byte{0x00}, cidBytes...)

	var buf bytes.Buffer

	// map(2)
	buf.WriteByte(0xa2)

	// key: "roots" (string of length 5)
	buf.WriteByte(0x65)
	buf.WriteString("roots")

	// value: array(1)
	buf.WriteByte(0x81)
	//   tag(42)
	buf.WriteByte(0xd8)
	buf.WriteByte(0x2a)
	//   bytes(35)
	buf.WriteByte(0x58)
	buf.WriteByte(byte(len(cidWithPrefix)))
	buf.Write(cidWithPrefix)

	// key: "version" (string of length 7)
	buf.WriteByte(0x67)
	buf.WriteString("version")

	// value: uint(1)
	buf.WriteByte(0x01)

	return buf.Bytes()
}

// encodeVarint encodes a uint64 as a varint byte slice.
func encodeVarint(v uint64) []byte {
	if v < 128 {
		return []byte{byte(v)}
	}
	var buf []byte
	for v >= 128 {
		buf = append(buf, byte(v)|0x80)
		v >>= 7
	}
	buf = append(buf, byte(v))
	return buf
}
